### PR TITLE
fix #11

### LINKED ISSUE #11: Panic
Converting `シークヮーサー` to hiragana panics:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /dev/shm/tmpfs/wana_kana_rust/src/utils/katakana_to_hiragana.rs:61:28
```

To reproduce:

```rust
use wana_kana::ConvertJapanese;

fn main() {
    "シークヮーサー".to_hiragana();
}
```

### PR DESCRIPTION
**Pull request by JojiiOfficial**
Fixes #11

### CODE REVIEW

File: src/is_hiragana.rs [hunk 1]
```diff
@@ -11,10 +11,7 @@
 use crate::utils::is_char_hiragana::*;
 
 pub fn is_hiragana(input: &str) -> bool {
-    if input.is_empty() {
-        return false;
-    }
-    input.chars().all(is_char_hiragana)
+    !input.is_empty() && input.chars().all(is_char_hiragana)
```
Comment (PSeitz) [inline src/is_hiragana.rs]: I think the previous version is more readable

File: Cargo.toml [hunk 2]
```diff
@@ -13,16 +13,17 @@ version = "2.1.0"
...
-regex = { version = "1.3.1", optional = true }
+regex = { version = "1.7.0", optional = true }
 
 [dev-dependencies]
 speculate = "0.1.2"
 
 [features]
 enable_regex = ["regex"]
+tokenize = ["itertools"]
 default = []
```
Comment (PSeitz) [inline Cargo.toml:27]: tokenize should be a default feature

File: src/is_japanese.rs [hunk 3]
```diff
@@ -16,10 +16,7 @@ use crate::utils::is_char_japanese::*;
 use regex::Regex;
 
 pub fn is_japanese(input: &str) -> bool {
-    if input.is_empty() {
-        return false;
-    }
-    input.chars().all(is_char_japanese)
+    !input.is_empty() && input.chars().all(is_char_japanese)
```
Comment (PSeitz) [inline src/is_japanese.rs]: I think the previous version is more readable

**Review by PSeitz — COMMENTED** [review]
sorry for the late review, I forgot about the PR

File: src/is_hiragana.rs (hunk 1 above)
Comment (JojiiOfficial) [reply src/is_hiragana.rs]: Imo this is cleaner as the function represents a single bool expression that is written there. But I actually didn't intend to put this into this PR.

File: Cargo.toml (hunk 2 above)
Comment (JojiiOfficial) [reply Cargo.toml:27]: I personally use this only to convert kana and I think there lots of users of wanakana use it for this purpose only as well. But this also wasn't intended to be added to this pr.

File: src/is_hiragana.rs (hunk 1 above)
Comment (PSeitz) [reply src/is_hiragana.rs]: The single bool expression is the reason why it's less readable.
What happens on empty input? -> need to look at the whole bool expression instead of one line

What happens on other input? -> need to look at the whole bool expression instead of one line

Clean is quite subjective, but according to the "Clean Code" book this is discouraged (The Stepdown Rule)

File: Cargo.toml (hunk 2 above)
Comment (PSeitz) [reply Cargo.toml:27]: I have no problem to add this to the lib. Is there a problem with the itertools dependency? (no_std support?)

Comment (JojiiOfficial) [reply Cargo.toml:27]: I just prefer to have as less dependencies as possible in my code or better said I see it as a good practice to keep them as few as possible and I don't need `tokenize` in my current project.

File: src/is_hiragana.rs (hunk 1 above)
Comment (JojiiOfficial) [reply src/is_hiragana.rs]: Yeah its indeed pretty subjective and as I didn't intend to PR this part anyways I'm fine with keeping it the way it was. I just changed it while going through the code when adjusting the lib for my needs.

Comment (PSeitz) [reply src/is_hiragana.rs]: can you update the PR? LGTM to me, except the bool expression

**Comment by PSeitz** [comment]
Thanks!
